Feature lesson9
MariaRakhmanava/SauceDemoNew pull request #3
Opened 2021-06-02 21:15 UTC by MariaRakhmanava

2021-06-04 12:24 UTC, vchesnakoutest requested changes
please make fixes and send to review again

2021-06-04 12:24 UTC, vchesnakoutest commented on src/main/java/consts/iURLsOfPages.java
> +public interface iURLsOfPages {
названия классов\интерфейсов с большой буквы в стиле: IPagesUrls

2021-06-04 12:24 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +        String locator = REMOVE_BUTTON.substring(48);
для чего тут используется .substring(48) ?

2021-06-04 12:24 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +        for (WebElement x : allProducts) {
for (WebElement productElement: allProducts)

2021-06-04 12:24 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    public CheckoutCustomerInformationPage goToCheckout() {
clickCheckoutButton() - чтобы явно понимать, что мы переходим через нажатие по кнопке

2021-06-04 12:24 UTC, vchesnakoutest commented on src/main/java/pages/CheckoutCompletePage.java
> +    public CheckoutOverviewPage goToThePreviousPage() {
clickBackHomeButton()

2021-06-04 12:24 UTC, vchesnakoutest commented on src/main/java/pages/CheckoutCustomerInformationPage.java
> +    }
спорный момент нужны ли нам эти методы. по сути тут тоже идет некая дубликация кода. лучше сделать один метод, а в него через тесты передавать пустые параметры.

2021-06-04 12:24 UTC, vchesnakoutest commented on src/main/java/pages/CheckoutCustomerInformationPage.java
> +    public CartPage cancelAndGoToThePreviousPage() {
сlickCancelButton()

2021-06-04 12:24 UTC, vchesnakoutest commented on src/main/java/pages/CheckoutOverviewPage.java
> +    public CheckoutCustomerInformationPage cancelAndGoToThePreviousPage() {
clickCancelButton

2021-06-04 12:24 UTC, vchesnakoutest commented on src/main/java/pages/CheckoutOverviewPage.java
> +    public CheckoutCompletePage finishCheckout() {
clickFinishButton

2021-06-04 12:24 UTC, vchesnakoutest commented on src/main/java/pages/GeneralPartPage.java
> +abstract class GeneralPartPage extends BasePage {
GeneralPartPage лучше назвать в духе HeaderMenuPage или что-то похожее

2021-06-04 12:24 UTC, vchesnakoutest commented on src/main/java/pages/GeneralPartPage.java
> +        openMenuButton.click();
эту часть лучше вынести в отдельный метод и вызывать его в остальных тестах

2021-06-04 12:24 UTC, vchesnakoutest commented on src/main/java/pages/ProductsPage.java
> +    public By getProductLink(String productName) {
getProductLinkLocator

2021-06-04 12:24 UTC, vchesnakoutest commented on src/main/java/pages/ProductsPage.java
> +    public void goToProductDetailsPage(String productName) {
clickProductDetailsButton

2021-06-04 12:24 UTC, vchesnakoutest commented on src/test/java/tests/CheckoutOverviewTest.java
> +        }
я бы создал для этого отдельный метод в классе со страницами

2021-06-04 12:24 UTC, vchesnakoutest commented on src/test/java/tests/LoginTest.java
> +        loginPage.closeErrorMessage();
это действие после ассерта является лишним. т.к мы выполнили уже необходимую для нас проверку в тесте (в остальных тестах проверь тоже)

2021-06-04 14:46 UTC, MariaRakhmanava commented on src/main/java/pages/CartPage.java
> +        String locator = REMOVE_BUTTON.substring(48);
Вырезала себе нужные локаторы из уже имеющихся по надобности, чтобы не дублировать одинаковый код в разных локаторах, но с page factory pattern в этом отпала необходимость, согласна с тобой, переделала

2021-06-04 14:48 UTC, MariaRakhmanava commented on src/main/java/pages/CheckoutCustomerInformationPage.java
> +    }
Опять согласна, явное дублирование кода, зато как ясно читается:))) переделала

2021-06-04 14:51 UTC, MariaRakhmanava commented on src/test/java/tests/LoginTest.java
> +        loginPage.closeErrorMessage();
раньше я здесь после сообщения еще проверяла возможность повторного ввода, а для этого нужно было закрывать сообщение об ошибке, но потом убрала ту проверку, она в принципе наслаивается, а эту инструкцию о закрытии error message оставила по невнимательности, балда

2021-06-04 14:52 UTC, MariaRakhmanava commented on src/test/java/tests/CheckoutOverviewTest.java
> +        }
я в принципе дала методы добавить товар в корзину и добавить все сразу, добавить несколько за раз будет уже дубликацией, поэтому этот кусок переделала, но немного иначе

2021-06-08 10:17 UTC, vchesnakoutest approved these changes
please make fix and merge

2021-06-08 10:17 UTC, vchesnakoutest commented on src/main/java/pages/CheckoutCustomerInformationPage.java
> +    public void enter(String firstName, String lastName, String postalCode) {
enterUserInformation или что-то похожее

2021-06-08 10:39 UTC, merged